name: FlutterGalleryApp
description: Amazing Flutter Project
author: Deep27

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: any
  connectivity: ^0.4.8+6
  cupertino_icons: ^0.1.2
  csv: ^4.0.3
  gallery_saver: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
